---
name: spark-boshrelease
director_uuid: 53e56169-85eb-428f-b2ef-04caf08525bb

releases:
- name: spark-boshrelease
  version: latest

compilation:
  workers: 2
  network: jenkins-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: jenkins-common
  network: jenkins-network
  size: 3
  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest
  cloud_properties:
    name: random

networks:
- name: jenkins-network
  subnets:
<% (0..28).each_with_index do |i| %>
  - range: 10.244.1.<%= i*4 %>/30
    reserved:
      - 10.244.1.<%= i*4 + 1 %>
    static:
      - 10.244.1.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>
<% (29..61).each_with_index do |i| %>
  - range: 10.244.1.<%= i*4 %>/30
    reserved:
      - 10.244.1.<%= i*4 + 1 %>
    cloud_properties:
      name: random
<% end %>
<% (62..63).each_with_index do |i| %>
  - range: 10.244.1.<%= i*4 %>/30
    reserved:
      - 10.244.1.<%= i*4 + 1 %>
    static:
      - 10.244.1.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>

jobs:
- name: jenkins-master
  template:
  - jenkins_master
  instances: 1
  resource_pool: jenkins-common
  networks:
  - name: jenkins-network
    static_ips:
    - 10.244.1.14
  persistent_disk: 4096

- name: mesos-master
  template:
  - mesos-master
  instances: 1
  resource_pool: jenkins-common
  networks:
  - name: jenkins-network
    static_ips:
    - 10.244.1.6
  persistent_disk: 4096

- name: mesos-slave
  template:
  - mesos-slave
  instances: 1
  resource_pool: jenkins-common
  networks:
  - name: jenkins-network
  persistent_disk: 4096

properties:
  jenkins:
    admin:
      password: password
  mesos:
    cluster:
      name: Bosh Mesos Cluster
    master:
      ip: 10.244.1.6
      port: 5050
    slave:
      port: 5051
