<% num_zookeepers = 3 %>
<% num_kafka_brokers = 1 %>
<% deployment_name = "kafka-aws" %>
<% kafka_broker_ip = %>
<% os = "ubuntu" %>
<% tld = "microbosh" %>
<% release_name = "insightfactory-boshrelease" %>
<% director_uuid = "6c72a227-45c9-4df6-8973-7172b954812a" %>
---

compilation:
  cloud_properties:
    instance_type: m1.xlarge
  network: default
  reuse_compilation_vms: true
  workers: 6
name:  <%= deployment_name %>
director_uuid: <%= director_uuid %>

jobs:
- name: zookeeper
  networks:
  - name: default
    default: [dns, gateway]
    static_ips: null
  resource_pool: zookeeper
  template: zookeeper
  instances: <%= num_zookeepers %>

- name: kafka
  networks:
  - name: default
    default: [dns, gateway]
  - name: elastic
    static_ips:
      - <%= kafka_broker_ip %>
  resource_pool: kafka
  template: kafka
  instances: <%= num_kafka_brokers  %>

meta:
  environment: <%= deployment_name %>
  stemcell:
    name: bosh-aws-xen-<%= os %>
    version: latest

networks:
- cloud_properties: {}
  name: elastic
  type: vip
- cloud_properties:
    security_groups:
    - hadoop
  name: default
  type: dynamic


releases:
- name: <%= release_name %>
  version: latest

resource_pools:
  - name: zookeeper
    network: default
    size: <%= num_zookeepers %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.medium

  - name: kafka
    network: default
    size: <%= num_kafka_brokers %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.large


properties:
  zookeeper:
    servers:
      <% num_zookeepers.times do |i| %>
      <%= "- #{i}.zookeeper.default.#{deployment_name}.#{tld}\n" %>
      <% end %>

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  update_watch_time: 1000-30000

