<% num_zookeepers = 3 %>
<% num_masters = 2 %>
<% num_hdfs_masters = 2 %>
<% num_slaves = 5 %>
<% num_clients = 1 %>
<% num_marathons = 2 %>
<% num_chronos = 2 %>
<% num_jenkins = 1 %>
<% num_cassandras = 1 %>
<% client_public_ip =  %>
<% deployment_name = "mesos-ha-hdfs-aws" %>
<% os = "ubuntu" %>
<% tld = "microbosh" %>
<% release_name = "insightfactory-boshrelease" %>
<% director_uuid = "6c72a227-45c9-4df6-8973-7172b954812a" %>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: <%= release_name %>
   version: latest

compilation:
  workers: 15
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.xlarge

update:
  canaries: 10
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 32
  serial: false

networks:
  - cloud_properties: {}
    name: elastic
    type: vip
  - cloud_properties:
      security_groups:
      - hadoop
    name: default
    type: dynamic

jobs:
  - name: zookeeper
    template: zookeeper
    instances: <%= num_zookeepers %>
    resource_pool: zookeeper
    networks:
      - name: default
        default: [dns, gateway]

  - name: mesos-master
    template: mesos-master
    instances: <%= num_masters %>
    resource_pool: master
    networks:
      - name: default
        default: [dns, gateway]

  - name: hdfs-master
    networks:
    - name: default
      default: [dns, gateway]
      static_ips: null
    resource_pool: hdfs-master
    template: namenode
    instances: 1

  - name: hdfs-smaster
    networks:
    - name: default
      default: [dns, gateway]
      static_ips: null
    resource_pool: hdfs-master
    template: secondarynamenode
    instances: 1

  - name: mesos-slave
    template:
      - mesos-slave
      - datanode
    instances: <%= num_slaves %>
    resource_pool: slave
    networks:
      - name: default
        default: [dns, gateway]

  - name: marathon
    template: marathon
    instances: <%= num_marathons %>
    resource_pool: marathon
    networks:
      - name: default
        default: [dns, gateway]

  - name: chronos
    template: chronos
    instances: <%= num_chronos %>
    resource_pool: chronos
    networks:
      - name: default
        default: [dns, gateway]

  - name: jenkins
    template: jenkins
    instances: <%= num_jenkins %>
    resource_pool: jenkins
    networks:
      - name: default
        default: [dns, gateway]

  - name: cassandra
    template: cassandra
    instances: <%= num_cassandras %>
    resource_pool: cassandra
    networks:
      - name: default
        default: [dns, gateway]

  - name: client
    networks:
    - name: default
      default: [dns, gateway]
    - name: elastic
      static_ips:
        - <%= client_public_ip %>
    resource_pool: client
    template: client
    instances: <%= num_clients %>

resource_pools:
  - name: zookeeper
    network: default
    size: <%= num_zookeepers %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.medium

  - name: master
    network: default
    size: <%= num_masters %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.medium

  - name: hdfs-master
    network: default
    size: <%= num_hdfs_masters %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.xlarge

  - name: slave
    network: default
    size: <%= num_slaves %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m2.2xlarge

  - name: marathon
    network: default
    size: <%= num_marathons %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.medium

  - name: chronos
    network: default
    size: <%= num_chronos %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.medium

  - name: jenkins
    network: default
    size: <%= num_jenkins %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.medium

  - name: cassandra
    network: default
    size: <%= num_cassandras %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.medium

  - name: client
    network: default
    size: <%= num_clients %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m1.large

properties:
  zookeeper:
    servers:
      <% num_zookeepers.times do |i| %>
      <%= "- #{i}.zookeeper.default.#{deployment_name}.#{tld}\n" %>
      <% end %>
  spark:
    masters: "0.spark-master.default.<%= deployment_name %>.<%= tld %>:7077,1.spark-master.default.<%= deployment_name %>.<%= tld %>:7077"
  hadoop:
    namenode:
      host: "0.hdfs-master.default.<%= deployment_name %>.<%= tld %>"
      port: 8020
    yarn:
      resourcemanager:
        resourcetracker:
          address: "0.yarn-master.default.<%= deployment_name %>.<%= tld %>"
        admin:
          address: "0.yarn-master.default.<%= deployment_name %>.<%= tld %>"
        hostname: "0.yarn-master.default.<%= deployment_name %>.<%= tld %>"
        scheduler:
          address: "0.yarn-master.default.<%= deployment_name %>.<%= tld %>"
        webapp:
          address: "0.yarn-master.default.<%= deployment_name %>.<%= tld %>"
        address: "0.yarn-master.default.<%= deployment_name %>.<%= tld %>"
      mapreduce:
        jobhistory:
          webapp:
            address: "0.yarn-master.default.<%= deployment_name %>.<%= tld %>"
          address: "0.yarn-master.default.<%= deployment_name %>.<%= tld %>"
      log:
        server:
          url: "http://0.yarn-master.default.<%= deployment_name %>.<%= tld %>:19888/jobhistory/logs"
