<% num_zookeepers = 3 %>
<% num_masters = 2 %>
<% num_slaves = 5 %>
<% num_clients = 1 %>
<% vpc_subnet_id = VPC_Subnet_ID %>
<% deployment_name = "spark-ha-aws-vpc" %>
<% os = "ubuntu-trusty-go_agent" %>
<% tld = "microbosh" %>
<% release_name = "insightfactory-boshrelease" %>
<% director_uuid = "fb1e4971-a406-4d02-8401-5b27c975f19b" %>
---

compilation:
  cloud_properties:
    instance_type: m3.xlarge
  network: default
  reuse_compilation_vms: true
  workers: 6
name:  <%= deployment_name %>
director_uuid: <%= director_uuid %>

jobs:
- name: zookeeper
  networks:
  - name: default
    default: [dns, gateway]
    static_ips: null
  resource_pool: zookeeper
  template: zookeeper
  instances: <%= num_zookeepers %>

- name: spark-master
  networks:
  - name: default
    default: [dns, gateway]
    static_ips: null
  resource_pool: master
  template: spark-master
  instances: <%= num_masters %>

- name: spark-slave
  networks:
  - name: default
    default: [dns, gateway]
    static_ips: null
  resource_pool: slave
  template: spark-slave
  instances: <%= num_slaves %>

- name: client
  networks:
  - name: default
    default: [dns, gateway]
    static_ips: null
  resource_pool: client
  template: client
  instances: <%= num_clients %>

meta:
  environment: <%= deployment_name %>
  stemcell:
    name: bosh-aws-xen-<%= os %>
    version: latest

networks:
- cloud_properties: {}
  subnet: <%= vpc_subnet_id %>
  type: manual
- cloud_properties:
    security_groups:
    - hadoop
  name: default
  type: dynamic


releases:
- name: <%= release_name %>
  version: latest

resource_pools:
  - name: zookeeper
    network: default
    size: <%= num_zookeepers %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m3.medium

  - name: master
    network: default
    size: <%= num_masters %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m3.xlarge

  - name: slave
    network: default
    size: <%= num_slaves %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m3.2xlarge

  - name: client
    network: default
    size: <%= num_clients %>
    stemcell:
      name: bosh-aws-xen-<%= os %>
      version: latest
    cloud_properties:
      instance_type: m3.large


properties:
  zookeeper:
    servers:
      <% num_zookeepers.times do |i| %>
      <%= "- #{i}.zookeeper.default.#{deployment_name}.#{tld}\n" %>
      <% end %>
  spark:
    masters: "0.spark-master.default.<%= deployment_name %>.<%= tld %>:7077,1.spark-master.default.<%= deployment_name %>.<%= tld %>:7077"

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  update_watch_time: 1000-30000

