---
packages:
- name: sasl
  version: 1
  sha1: !binary |-
    MTEyODE2MjNhNjhlOTFhYzcyYzU3MTFkZDViNDY4OThmOGZiNDUxNg==
  fingerprint: !binary |-
    MGJmNGE3ZjhjNzE0NWRiMmExNDNhMmY0YzE3MzA4M2I5NzNjZWY0Ng==
  dependencies: []
- name: scala
  version: 1
  sha1: !binary |-
    MzM1NGZmYTdhMWEyNDM3NGM0ZDkwMzRkYmY2OTI2YmVmOWRiMTg5NA==
  fingerprint: !binary |-
    ZjA5OTNlODM4MGI4NjI3ZTUyMzYwMjg3ZGQ1MjFmNTNhYmUwNzM2Zg==
  dependencies: []
- name: chronos
  version: 1
  sha1: !binary |-
    NTE2ZTIxYmUxMWFhZjQxZDE3Yjg1MjIzNDM2NDNiMTdhOTE5NzViMg==
  fingerprint: !binary |-
    NzFkOTExYTlmNjMyYzQ3OTYyZDQ3MmYwYzAzYWIwN2JlYzRjMDUwMw==
  dependencies: []
- name: hadoopmr
  version: 1
  sha1: !binary |-
    ZGRmODcwZTI5NThiMjEzODNjYWE2ZDY0YWY4N2FmM2I2M2RlMDg3OQ==
  fingerprint: !binary |-
    ZGZiMDhmYWI0YzM3ZTY1N2EzOWVmMjk1ZTM4OTcwOGE3Y2M3OTU4NQ==
  dependencies:
  - java
  - snappy
- name: nginx
  version: 1
  sha1: !binary |-
    NGU0M2JiNDYyMjVmNmQ4OTcyYjM0MDM3YzhhNDFkY2FjYTk4Y2ZhYQ==
  fingerprint: !binary |-
    ZjFiNWU4OTBmMTFmNTgwZDFkOWIyNTFiOTY0M2Y0M2IwMTU5M2QzOQ==
  dependencies: []
- name: zookeeper
  version: 1
  sha1: !binary |-
    N2U5NmJiMjRiMTJlNTUxOTdhZDc0OTA5ZTliOTBiNDJkOGIyYzFmOA==
  fingerprint: !binary |-
    MDI3YTk5ZGZmNzg4Nzg5ODE5ZDJmY2E4N2YwZGMwNjE2ODdhYTEyOQ==
  dependencies: []
- name: mesos
  version: 1
  sha1: !binary |-
    MDFhYTlmZTI0OGRhNmU5ZWFjZDlkNzkzZmE1NjZhZTI4ZGQyNDdlMw==
  fingerprint: !binary |-
    MjkzNTNjYmFhMjJlYWExYThmYmRjMGZmZTFkMjRmMzNlZjU3ZDgwYg==
  dependencies:
  - java
  - sasl
- name: pig
  version: 1
  sha1: !binary |-
    MzFmOTMwMThkNDhmODVjMzAwZmIzYmNlYWYyYWFkNDEwY2JmM2NlZg==
  fingerprint: !binary |-
    NzYxOWU0NzQzMDg5NmY2MDcyYWU5MDZkY2M1MDNlMzRhNjc5OTAwYg==
  dependencies:
  - hadoop
- name: jenkins
  version: 1
  sha1: !binary |-
    NTAwNzBjN2JiNWNlYjUwNjQ5MmFlMTUwOTBkZDgyMmNlOWNlY2RmYg==
  fingerprint: !binary |-
    N2Q4NjI5ZDlmNGZjOGJkNWM0ZmYyNTY5YjhkODVmMzcxMDhhZTMyZQ==
  dependencies: []
- name: cassandra
  version: 1
  sha1: !binary |-
    ZmVhYTI1MTk3YTJkMjllYjBlOTVjNGUxNWE0NTA2ZTkyYjQzODAzYQ==
  fingerprint: !binary |-
    ZmY1N2M0NzExYTVjMGRhZjkzNTY1MjJiMGY1ZjRhMTMyYjM3ODM1Ng==
  dependencies: []
- name: ruby
  version: 1
  sha1: !binary |-
    NDg2M2U4MTIwNGUwNzE1MTdlYTMxYzhiMDhhY2Y4NjNlMTI3NGRkNg==
  fingerprint: !binary |-
    MTI3NGQ3MWQzYzExMTkyMWNiN2VlODA3Njg4NzUwYmZhYjUyNzdjNw==
  dependencies: []
- name: spark
  version: 1
  sha1: !binary |-
    MGQ2ZTI0MmFhNzVhY2FhODEwZmIzOWE3YjRjNmVlZWE5YThjM2NmNg==
  fingerprint: !binary |-
    YTZhYjY4OGY4OTg3YmYyZGNmZmU5YjczY2M0ZjJjOTlhZDgwMmRhNg==
  dependencies: []
- name: marathon
  version: 1
  sha1: !binary |-
    ZGYzYTZiYWU2NDY5MDMzZWUwYzdlZjVjYjhjNjY5N2Y4NDZhYjVmMw==
  fingerprint: !binary |-
    ZmI0Yzc3ZmFjODEwNzUxNGZmOWQ1NjZhMzVjY2M3ODg1ZmI3ZWVkMw==
  dependencies: []
- name: node
  version: 1
  sha1: !binary |-
    MjZiMDdlOTgyMzkzYTMyNDY1YWE2ODkzNmY0ZDEwZDM3YWIwYjIxNw==
  fingerprint: !binary |-
    MzIwNGZjNjVlM2VkNDE2OWQ2YTgzNTFkYWI2MzJjMjYyMDRlZWUzYQ==
  dependencies: []
- name: java
  version: 1
  sha1: !binary |-
    MjY4YWZkMjU1NDM0NmMyZDA1Y2U0ODYwYjA0MTY0M2RiY2VmZDAxMQ==
  fingerprint: !binary |-
    YjMxNGQxZmFlY2M4Y2RiZmViMzQ1Yzg1Njg2OGE4NzM4MGUwMGMxZg==
  dependencies: []
- name: hadoop
  version: 1
  sha1: !binary |-
    NTdiYzc1YmFlODE1NmJhM2U3OWZkZTM0ZDhkODk5YTAyZGMxNWU5MA==
  fingerprint: !binary |-
    N2M0MDBlZTliNjBlYzg2NWU1ZGY3ZWE0MmYyZDQ1YTY1ZjY2ZmYxMA==
  dependencies:
  - java
  - snappy
- name: bosh-helpers
  version: 1
  sha1: !binary |-
    MjJkZGJmY2RhN2U3MmQzNTY4N2I3YjAxY2E2MmQ5N2QyZmQyMWY2Yg==
  fingerprint: !binary |-
    Mjg0ZDAyZTcwOTYzZTA4OWI1MmUyZDNlZDY4M2E3Yzg0M2VkMDk0Yg==
  dependencies: []
- name: git
  version: 1
  sha1: !binary |-
    Mzk1MDZiZTMzOTdiMmFjNDFmMTY5OWI0MmI2YmY4ZGVkMmU3ZThiYw==
  fingerprint: !binary |-
    NGVjZjQwYWVmYzFkNTg1ZTk4ODhlNmM3YWIxMGVhYWQ0MTYwNThmYw==
  dependencies: []
- name: sbt
  version: 1
  sha1: !binary |-
    YjFlNWNmYTNhMzg3MDAxM2M5YWFjOGY2MWQzMGI1MzFkYzQ5MzRlMA==
  fingerprint: !binary |-
    Nzc2MjhkNmQ1ZDFhZWIxYmQ1MzIxN2M2NmVmZjEwYmUxZmQ2ZWU3OA==
  dependencies: []
- name: hive
  version: 1
  sha1: !binary |-
    ODg4MmYyNGY2MjI0MTY5ODg3MGY2Zjc2YjJhZGQ1ZjYyZjNiNDgxYQ==
  fingerprint: !binary |-
    YmRmNzczOGMwMDljMGZlODI4MTFiYjQ0MDIwMWMwYzJjNWEzYzUwYw==
  dependencies:
  - hadoop
- name: snappy
  version: 1
  sha1: !binary |-
    YTc1MzJiMzRkN2ZiNzYxZjQyOWM4ODA1ZDY3MTJlODIwNWVkNmEwNA==
  fingerprint: !binary |-
    M2YxZWI0ZWNkNzVjZTI2MDkxOTNjOWM3NDkzZTY3NWIzMWQ3Y2I2ZQ==
  dependencies: []
jobs:
- name: yarn-resourcemanager
  version: 1
  fingerprint: !binary |-
    Y2U2NWJkZmM3NjRhNDM0OWYzYzkzZDg1MmQ4NWViYWMyOWNmNGIwYg==
  sha1: !binary |-
    NDc3NGI2YTdkNDZjZTllNzJjMjUwYjU4NTYwY2QzNzExYzkzZWJmMQ==
- name: spark-master
  version: 1
  fingerprint: !binary |-
    NzEyYTc0ZjhkNDhmOTYzMTg2YTNlMjVlZGU1ZDM2NTNjNDE2OWY2YQ==
  sha1: !binary |-
    ZmU2NzY0OGE2OWZmYTRmNDAwODAyZDViNWM2ZjQ5Y2E3NTE2M2RkNQ==
- name: client
  version: 1
  fingerprint: !binary |-
    MjlmODM0MTgyYmIwMzJmZmY3NzE3OTk4ZDhkZTU2YWQ3NmY4YTIyOA==
  sha1: !binary |-
    YmFjOTI1NzdhNjlhOGZhY2Q2MGY1NWQ5NzMzNGNlZTZkODI4MjUwNQ==
- name: secondarynamenode
  version: 1
  fingerprint: !binary |-
    ZWY5MTVjZGI2OWY5YjdiMGI5MWE5OTQxNjEzMTA2YmM4NDU3NmQxMQ==
  sha1: !binary |-
    ODgzZmIxZTVhNDlhZTg3YmFjOTk2YmQ1YmI0OGI5NTVhMzdmNDBlYw==
- name: yarn-nodemanager
  version: 1
  fingerprint: !binary |-
    ZGY5Mzk1Y2FkYzliNDBhNzhhMjg4OTE1MmM1OTI0NTVjMzNjMDY3OA==
  sha1: !binary |-
    OTY0NGY5YTlkYzRjMjJmNzU1NTI1MjI5MjIyZWQxMjBjMDMwZTQ0ZQ==
- name: mesos-slave
  version: 1
  fingerprint: !binary |-
    MTczZDlhYjhhMGFlY2JkNTAxMWI0NGZlMWRiNzY5NzM4NjI3ODkyNg==
  sha1: !binary |-
    OTIzMjg5YTIzOWE3MzEyNjgyMDk2MjMyOGE3Yzk0M2UyYWFjMDUxNw==
- name: chronos
  version: 1
  fingerprint: !binary |-
    ODY4NzlmOTZjYzdiMmQ3NmIwNTE3NjM5YjE2OTJkN2RjYTlmYTA2Yg==
  sha1: !binary |-
    ZGRiYmY3MjAzZjYxNjM2OTc5OWM2NTMzZGM2ZmMyYjE2MDZjM2YwZg==
- name: mesos-master
  version: 1
  fingerprint: !binary |-
    NDNlYTcxNDNhNDIyNjQzMWFlMDUzNzllNDU2MTQ0MGIxMmU0OWM2OA==
  sha1: !binary |-
    ZTk5MzUzNzE4YTJjZDI2MDQ5ODRlNjNjYmU3MmFiZDY0ZGQ2ZDc5MQ==
- name: secondarynamenodemr
  version: 1
  fingerprint: !binary |-
    YmVjY2I0NDk1ZWExZmYwZmQ3ZmI2YTgyNjAzNmQ5NGMxYjJkODFmMw==
  sha1: !binary |-
    OGQwOTQ5N2UwYTg4Y2E0OWMzMTIwMTJmOWYzYzc0ZTQzMjFiOWM2NQ==
- name: zookeeper
  version: 1
  fingerprint: !binary |-
    MThmNDdmNThkZGY1M2JmNmQwNWI2ZmFjNWIxYjYyNWZkMjA2NzkxZQ==
  sha1: !binary |-
    OGI5ZjYxNDQ5NDIwZDkxYTZmMDNlNTU5OWU2N2FjYWMyM2NiMzhmMA==
- name: jenkins
  version: 1
  fingerprint: !binary |-
    MDkwNDQ5NDc5YmQyN2U1MjUwNGQzZDJkZTNiYzJhNjA5OTljMDAyOA==
  sha1: !binary |-
    ODVhZWI3NDYwMWZiZTE4YzNlYmJjM2JmZmQ4NzJhMDljOWVlNWM1Mw==
- name: cassandra
  version: 1
  fingerprint: !binary |-
    YmY4ZWI0ZDhhY2I2NDFjNjQ0OTAwZjgwOTc4N2M4OWNhZTc3YTJlMQ==
  sha1: !binary |-
    NzZkZDJhYjc0YzdkY2VjNzVkNjU3OGRkN2E4ZWQyNWY3NjY0ZDhiNA==
- name: marathon
  version: 1
  fingerprint: !binary |-
    ODk1MDI5NWNhYjQ3MTVmYWNhNjYyYzUyZGY1YmE1ZmM1OWMzNDEyMQ==
  sha1: !binary |-
    MTM1ZGFlZDMzNDU2NzM0NzYyZjc5NjgyMGY5MzNiMTdlYWQ4NWRhYg==
- name: namenodemr
  version: 1
  fingerprint: !binary |-
    OTY3ZmUxNTQ5MTMxMzNiNjM4OTE4NWMyYTg3ZGU2MDViNzZhYTUyMw==
  sha1: !binary |-
    YTE4NmM4YTRhZGYxZTlhMTY5YTgwOTkwYzRlZDY3NDA0ODcxZmFjNw==
- name: tasktracker
  version: 1
  fingerprint: !binary |-
    NmNmNDgwODM0ZWY1ZDA4MjM5MzZjNDQ3MzZhMTBjMjNmZTUzMWYxMA==
  sha1: !binary |-
    YzA4ZmU3MWMzYTUxZjZlNmYwY2EzNDRmY2YzNDQyYmUzZGFjNTUyOA==
- name: spark-slave
  version: 1
  fingerprint: !binary |-
    MTYyOTRjOWU2NTIzY2U1MWQ3YmZhMGNjNmIzNTMzNTU4NTVlYTg4ZQ==
  sha1: !binary |-
    YjFkN2VmNmEyODZjZTliZjgyNzM4YjdjYjE3YmRhYzYyODdjNDA5OQ==
- name: namenode
  version: 1
  fingerprint: !binary |-
    Y2NlM2QwN2FlMGRhZGJhY2YwNWNkNzQxM2ZiY2ZjNTZhZDY5NTRjYQ==
  sha1: !binary |-
    Mzk4NGFhYTRmNzUxYmI0Zjg5NzhjMDFhMDc3ZjllYjlhNjZmOTcwMg==
- name: jobtracker
  version: 1
  fingerprint: !binary |-
    ODcyOGMyM2I2ODA4YzM3ODQyZDk3ZDVhZWU3NzcyNjIyMzA3OWU3OQ==
  sha1: !binary |-
    ODBhMWNkNjQxZTEyNjEzN2I3YTQwNDVmYTcyY2JhMmM3OGFlNTQxNA==
- name: datanodemr
  version: 1
  fingerprint: !binary |-
    ZmJiYTgwNjcxZDY5NDQ3NWIxMmQxZWRmZWQ2MmVhYThhNTY0ZGVmOA==
  sha1: !binary |-
    MzNmOTA3MDRkZDdiMmY3NmY3ZmRkOTFiODBiNzIwZDk5NTM5OGE1Nw==
- name: mapreduce-jobhistory
  version: 1
  fingerprint: !binary |-
    YWFjMGI4ZTRmN2VlOTMyMDQ5YjIwM2YwYThkYjVkOTU2OWU0MDMxNQ==
  sha1: !binary |-
    ZGU0MDM5NTI4YzYxNjljNDZkYjIzYmFiMzI4M2VmZGUwMjIyNGJlOA==
- name: datanode
  version: 1
  fingerprint: !binary |-
    YzMwZTUwZTliMWFjMmQzNGQzZTM0ZjlkOGU4ODFmZTk5ODAwMjE4YQ==
  sha1: !binary |-
    YTE3YWFjZTRjM2Y5MGQ2YmJkMzc3ZDE0ZWY2Yjk5YWNjOWE3ODQyYw==
commit_hash: edc78942
uncommitted_changes: true
name: insightfactory-boshrelease
version: 2
