---
packages:
- name: sasl
  version: 1
  sha1: !binary |-
    ZWRjM2FmYzk2YTVkYzFkZTFhMGE1YmFkM2U5MmI5ODVmOGYxMTFkYg==
  fingerprint: !binary |-
    MGJmNGE3ZjhjNzE0NWRiMmExNDNhMmY0YzE3MzA4M2I5NzNjZWY0Ng==
  dependencies: []
- name: scala
  version: 1
  sha1: !binary |-
    MTFkNDAzNTZmOGQzMjY4ZWI3NmRmMzkzNmY0YWZlMWUzMjdhZDhkNg==
  fingerprint: !binary |-
    ZjA5OTNlODM4MGI4NjI3ZTUyMzYwMjg3ZGQ1MjFmNTNhYmUwNzM2Zg==
  dependencies: []
- name: chronos
  version: 1
  sha1: !binary |-
    MTA1MjZkOGMzYjFiMzBkMDZiMzNiYTIzZjNkYTM0ZTk4YjYxZjQ2Mw==
  fingerprint: !binary |-
    NzFkOTExYTlmNjMyYzQ3OTYyZDQ3MmYwYzAzYWIwN2JlYzRjMDUwMw==
  dependencies: []
- name: hadoopmr
  version: 1
  sha1: !binary |-
    ZWZmMDQ1NDU4NWM2ZDI0ZGE2ZDg5OTgyOWI0YTk3Yzc4MmNlMDVmYg==
  fingerprint: !binary |-
    ZGZiMDhmYWI0YzM3ZTY1N2EzOWVmMjk1ZTM4OTcwOGE3Y2M3OTU4NQ==
  dependencies:
  - java
  - snappy
- name: nginx
  version: 1
  sha1: !binary |-
    MmMyNGZhYjVjZTMxYmZlMGU3MjdlMWVjZWUzYzM1NjJhNDM4M2JjYg==
  fingerprint: !binary |-
    ZjFiNWU4OTBmMTFmNTgwZDFkOWIyNTFiOTY0M2Y0M2IwMTU5M2QzOQ==
  dependencies: []
- name: zookeeper
  version: 1
  sha1: !binary |-
    OWI5ODUyODVjNGM1Y2FkOGU4NmQ0MDcyZTM2ZjU1MjRjMjYxMjM3MQ==
  fingerprint: !binary |-
    MDI3YTk5ZGZmNzg4Nzg5ODE5ZDJmY2E4N2YwZGMwNjE2ODdhYTEyOQ==
  dependencies: []
- name: mesos
  version: 1
  sha1: !binary |-
    ZjA0YjlhMjk3MWM3Zjc4Yzc0NTc3ZDIxMzVjMDk5YzM4NTU1ZDU2YQ==
  fingerprint: !binary |-
    MjkzNTNjYmFhMjJlYWExYThmYmRjMGZmZTFkMjRmMzNlZjU3ZDgwYg==
  dependencies:
  - java
  - sasl
- name: pig
  version: 1
  sha1: !binary |-
    OGQ0ZDFmYmVkYWYwYzg2OTEzNjg5MDliMTAxM2NhOTE2ZjM2MWQxYQ==
  fingerprint: !binary |-
    NzYxOWU0NzQzMDg5NmY2MDcyYWU5MDZkY2M1MDNlMzRhNjc5OTAwYg==
  dependencies:
  - hadoop
- name: jenkins
  version: 1
  sha1: !binary |-
    YmUzNmEzNmY3ZWQ3MmMxYmQ1MmY5NmE5MTkwOTYzYjJjMzE4YjkwOQ==
  fingerprint: !binary |-
    N2Q4NjI5ZDlmNGZjOGJkNWM0ZmYyNTY5YjhkODVmMzcxMDhhZTMyZQ==
  dependencies: []
- name: cassandra
  version: 1
  sha1: !binary |-
    MTE1NzY0N2RmZTBkMThjNzRhNGZkYWNlNjRkOThiYjVmYjg5ZWZhNw==
  fingerprint: !binary |-
    ZmY1N2M0NzExYTVjMGRhZjkzNTY1MjJiMGY1ZjRhMTMyYjM3ODM1Ng==
  dependencies: []
- name: ruby
  version: 1
  sha1: !binary |-
    NGNkMmUzYzU3YzIwMGVjZTM2YmEzZDY0NjAzZmE4NjYzN2JhMzM3Mg==
  fingerprint: !binary |-
    MTI3NGQ3MWQzYzExMTkyMWNiN2VlODA3Njg4NzUwYmZhYjUyNzdjNw==
  dependencies: []
- name: spark
  version: 1
  sha1: !binary |-
    MGU3YjcwZjQzOWQ1MTkyZjkwMzllMjAxZWIxNjBiMDgxODE5YzYyNA==
  fingerprint: !binary |-
    YTZhYjY4OGY4OTg3YmYyZGNmZmU5YjczY2M0ZjJjOTlhZDgwMmRhNg==
  dependencies: []
- name: marathon
  version: 1
  sha1: !binary |-
    NDIxMmUwNTNlNjFmYzE1OTRlZmRiN2UyZTBlYmJkYjgzMzIzZmU2NQ==
  fingerprint: !binary |-
    ZmI0Yzc3ZmFjODEwNzUxNGZmOWQ1NjZhMzVjY2M3ODg1ZmI3ZWVkMw==
  dependencies: []
- name: node
  version: 1
  sha1: !binary |-
    ZjBmZDNlMDkzZDI1OTg0YjU2Y2RiYWYxOThjOTYxYzIzMTE0Yjg0Ng==
  fingerprint: !binary |-
    MzIwNGZjNjVlM2VkNDE2OWQ2YTgzNTFkYWI2MzJjMjYyMDRlZWUzYQ==
  dependencies: []
- name: java
  version: 1
  sha1: !binary |-
    MmUwYmJjNzA1YTM2ZTg0NmYzYWNhNDJlNzM1MWE4ODg3ODY4YjEyMA==
  fingerprint: !binary |-
    YjMxNGQxZmFlY2M4Y2RiZmViMzQ1Yzg1Njg2OGE4NzM4MGUwMGMxZg==
  dependencies: []
- name: hadoop
  version: 1
  sha1: !binary |-
    YjhhYzY1YTE3YzE2MmVkNmMxMDg4ZDBhMTFkOWU4MzZmZTBkOTZlYw==
  fingerprint: !binary |-
    N2M0MDBlZTliNjBlYzg2NWU1ZGY3ZWE0MmYyZDQ1YTY1ZjY2ZmYxMA==
  dependencies:
  - java
  - snappy
- name: bosh-helpers
  version: 1
  sha1: !binary |-
    N2ExYWRiNjJhMDQ4MTNkMWY5MTYyNGU5MjgxYmU4ODE0MWQwZjBlZQ==
  fingerprint: !binary |-
    Mjg0ZDAyZTcwOTYzZTA4OWI1MmUyZDNlZDY4M2E3Yzg0M2VkMDk0Yg==
  dependencies: []
- name: git
  version: 1
  sha1: !binary |-
    MDAzYWIwZGM3NmZkZWZhNzg1ZjY0MzQwZjg0MjZkYWYyM2JjMDI5Yw==
  fingerprint: !binary |-
    NGVjZjQwYWVmYzFkNTg1ZTk4ODhlNmM3YWIxMGVhYWQ0MTYwNThmYw==
  dependencies: []
- name: sbt
  version: 1
  sha1: !binary |-
    YmQwNjhjMjE1MGE2Njc5NGIwMzBmYTgwZmU1NjMzOGMyMGVjMmEzMg==
  fingerprint: !binary |-
    Nzc2MjhkNmQ1ZDFhZWIxYmQ1MzIxN2M2NmVmZjEwYmUxZmQ2ZWU3OA==
  dependencies: []
- name: hive
  version: 1
  sha1: !binary |-
    MGYyNGQ0YWNhNWM0NDMxOTA2NWI5Njc0Yzc4NDUyYWMwOWE1ZTg2Yg==
  fingerprint: !binary |-
    YmRmNzczOGMwMDljMGZlODI4MTFiYjQ0MDIwMWMwYzJjNWEzYzUwYw==
  dependencies:
  - hadoop
- name: snappy
  version: 1
  sha1: !binary |-
    YTJlMzU4NDVjZDg0YjBlZTNkYzQ0Y2ZiYmE2ZDM2ZDQyY2FjYzRhMA==
  fingerprint: !binary |-
    M2YxZWI0ZWNkNzVjZTI2MDkxOTNjOWM3NDkzZTY3NWIzMWQ3Y2I2ZQ==
  dependencies: []
jobs:
- name: yarn-resourcemanager
  version: 1
  fingerprint: !binary |-
    Y2U2NWJkZmM3NjRhNDM0OWYzYzkzZDg1MmQ4NWViYWMyOWNmNGIwYg==
  sha1: !binary |-
    NmQ4NWY4ZWI4MjQ3NjMzNTg0ZGJlYTJjNDMzOGZjZWI4OGRiMmNlZA==
- name: spark-master
  version: 1
  fingerprint: !binary |-
    NzEyYTc0ZjhkNDhmOTYzMTg2YTNlMjVlZGU1ZDM2NTNjNDE2OWY2YQ==
  sha1: !binary |-
    YzY4YTljMTg2NmU5MmNmMDM5ZDE1NzljYjAzMjRiNTczMjNiNTJiZA==
- name: client
  version: 1
  fingerprint: !binary |-
    MjlmODM0MTgyYmIwMzJmZmY3NzE3OTk4ZDhkZTU2YWQ3NmY4YTIyOA==
  sha1: !binary |-
    OGQzMWUwM2I5NTA4MTZmNWUwMTQ3MDc0Zjg1YTkxZmVjMjI0NmIyOA==
- name: secondarynamenode
  version: 1
  fingerprint: !binary |-
    ZWY5MTVjZGI2OWY5YjdiMGI5MWE5OTQxNjEzMTA2YmM4NDU3NmQxMQ==
  sha1: !binary |-
    NTJlYzVjNjc5OTY0NGE4NTQwOGQxNGRjZjI3NGMzZGQxMzZlY2EzOQ==
- name: yarn-nodemanager
  version: 1
  fingerprint: !binary |-
    ZGY5Mzk1Y2FkYzliNDBhNzhhMjg4OTE1MmM1OTI0NTVjMzNjMDY3OA==
  sha1: !binary |-
    YTNlMmExZDQzMmEwYjNhMTY4MGRmMTFiZDhhOGQ1ZGMyYjhhNGMxNA==
- name: mesos-slave
  version: 1
  fingerprint: !binary |-
    MTczZDlhYjhhMGFlY2JkNTAxMWI0NGZlMWRiNzY5NzM4NjI3ODkyNg==
  sha1: !binary |-
    OTY5MDlmNjgwYzIyYzk4MGU2YzEzNTI5OWJkMTdhZGMxZDgxMGEzNQ==
- name: chronos
  version: 1
  fingerprint: !binary |-
    ODY4NzlmOTZjYzdiMmQ3NmIwNTE3NjM5YjE2OTJkN2RjYTlmYTA2Yg==
  sha1: !binary |-
    MmE0YTczYmFmZjgyYWY0NjU5OWZkNTFmNDExMDc0Y2UwYmRkMjUyZg==
- name: mesos-master
  version: 1
  fingerprint: !binary |-
    NDNlYTcxNDNhNDIyNjQzMWFlMDUzNzllNDU2MTQ0MGIxMmU0OWM2OA==
  sha1: !binary |-
    OTg2NTJiYzQzMDA0YTFiMDhmYTU4NTQ5Mzc2Mzg3YWJmZGQxZjI5Ng==
- name: secondarynamenodemr
  version: 1
  fingerprint: !binary |-
    YmVjY2I0NDk1ZWExZmYwZmQ3ZmI2YTgyNjAzNmQ5NGMxYjJkODFmMw==
  sha1: !binary |-
    ODhkNjgyNzUzOTk3ZWY5OTFkNjA0ZDIxNTMyMTA2MTA4MzY4MmI2Mw==
- name: zookeeper
  version: 1
  fingerprint: !binary |-
    MThmNDdmNThkZGY1M2JmNmQwNWI2ZmFjNWIxYjYyNWZkMjA2NzkxZQ==
  sha1: !binary |-
    ZjI3YWRhOWFlMmEyNDU3YTkxYmFiNmE2NGU4NjRhYmY2NmJlYjkyMg==
- name: jenkins
  version: 1
  fingerprint: !binary |-
    MDkwNDQ5NDc5YmQyN2U1MjUwNGQzZDJkZTNiYzJhNjA5OTljMDAyOA==
  sha1: !binary |-
    MWJjNmJjODVhZDM1NjY2MzdiMDVkNjE2YmE5OTRlMmExY2NiM2NlYg==
- name: cassandra
  version: 1
  fingerprint: !binary |-
    YmY4ZWI0ZDhhY2I2NDFjNjQ0OTAwZjgwOTc4N2M4OWNhZTc3YTJlMQ==
  sha1: !binary |-
    Yjk0ZGQ4YTFlMWFmYzE5NjZhOTlhZTQwZGY2ODNjNWY2ZjcxMWNmMg==
- name: marathon
  version: 1
  fingerprint: !binary |-
    ODk1MDI5NWNhYjQ3MTVmYWNhNjYyYzUyZGY1YmE1ZmM1OWMzNDEyMQ==
  sha1: !binary |-
    MTFlYzg2MGNhOTI1NDZlODcxNTYwN2FjOGMxMTU2MzY4NmVkNjliMg==
- name: namenodemr
  version: 1
  fingerprint: !binary |-
    OTY3ZmUxNTQ5MTMxMzNiNjM4OTE4NWMyYTg3ZGU2MDViNzZhYTUyMw==
  sha1: !binary |-
    OGRmZWJmM2JmNGU4NTA5ODY4MjhmYzczZTg1ZmE1MTAyNjk5ZGQ3OA==
- name: tasktracker
  version: 1
  fingerprint: !binary |-
    NmNmNDgwODM0ZWY1ZDA4MjM5MzZjNDQ3MzZhMTBjMjNmZTUzMWYxMA==
  sha1: !binary |-
    MzI5M2JlMDMxMjA0NzRhOTIwNWE1OTU5OTM1MmM3NDExODU0Yjg4Nw==
- name: spark-slave
  version: 1
  fingerprint: !binary |-
    MTYyOTRjOWU2NTIzY2U1MWQ3YmZhMGNjNmIzNTMzNTU4NTVlYTg4ZQ==
  sha1: !binary |-
    OGRkMGNhYTA0NTk0MzJhM2E2MDJiZGVlOWM0ZjM4NWMwZWE5OWY4Mg==
- name: namenode
  version: 1
  fingerprint: !binary |-
    Y2NlM2QwN2FlMGRhZGJhY2YwNWNkNzQxM2ZiY2ZjNTZhZDY5NTRjYQ==
  sha1: !binary |-
    MjExNmYyNzBjNjA4MTM1MThiMzFmZGJiNzA3OTZjYzA4ZDViZDU4OA==
- name: jobtracker
  version: 1
  fingerprint: !binary |-
    ODcyOGMyM2I2ODA4YzM3ODQyZDk3ZDVhZWU3NzcyNjIyMzA3OWU3OQ==
  sha1: !binary |-
    ZDYwNjE3MzQ1Yzc5ZjZlYTlkNzZlMmY2NDg5MGEwNzIzZGFkYTZiYg==
- name: datanodemr
  version: 1
  fingerprint: !binary |-
    ZmJiYTgwNjcxZDY5NDQ3NWIxMmQxZWRmZWQ2MmVhYThhNTY0ZGVmOA==
  sha1: !binary |-
    MzIyZDFhZTczMzQ3OWYxNDEyMDI4NTYyMzRjNzU1ZmU0NmExNGM3OQ==
- name: mapreduce-jobhistory
  version: 1
  fingerprint: !binary |-
    YWFjMGI4ZTRmN2VlOTMyMDQ5YjIwM2YwYThkYjVkOTU2OWU0MDMxNQ==
  sha1: !binary |-
    YzQwNTI1OWQyYjA4OTYyMDE1ZmVmMDcxN2VjZDAzYWUxMDBlYmQyNQ==
- name: datanode
  version: 1
  fingerprint: !binary |-
    YzMwZTUwZTliMWFjMmQzNGQzZTM0ZjlkOGU4ODFmZTk5ODAwMjE4YQ==
  sha1: !binary |-
    OTVmMGU3M2M2NzJjZGU1MmY2MjIxZDU5NWFmMDlkMGI4ZTExNDBhMg==
commit_hash: 1a887487
uncommitted_changes: true
name: insightfactory-boshrelease
version: 2
